name: Build LaTeX Document

on:
  push:
    branches:
      - main  # Set this to your default branch
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex  # Replace with your main LaTeX file

    - name: Compile LaTeX Document
      run: latexmk -pdf main.tex  # Replace with your LaTeX build command

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./main.pdf  # Replace with the path to your generated PDF
        asset_name: main.pdf
        asset_content_type: application/pdf
