name: Create Release and Upload PDF

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Workflow Run ID to download artifacts from'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download PDF from Artifacts
      uses: actions/download-artifact@v3
      with:
        name: compiled-pdf
        workflow_run_id: ${{ github.event.inputs.run_id }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'release-${{ github.run_id }}'  # Customize this tag as needed
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./main.pdf
        asset_name: main.pdf
        asset_content_type: application/pdf
