name: Create Release and Upload PDF

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download PDF from Artifacts
      uses: actions/download-artifact@v3
      with:
        name: compiled-pdf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'release-${{ github.run_id }}'  # You can customize this tag
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./main.pdf
        asset_name: main.pdf
        asset_content_type: application/pdf
